# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=140)),
                ('author', models.CharField(max_length=20)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
